set
client_min_messages = WARNING;
alter table if exists app_permission drop constraint if exists FK_PERMISSION__CREATED_BY;
alter table if exists app_permission drop constraint if exists FK_PERMISSION__MODIFIED_BY;
alter table if exists app_role drop constraint if exists FK_ROLE__CREATED_BY;
alter table if exists app_role drop constraint if exists FK_ROLE__MODIFIED_BY;
alter table if exists app_role_permission drop constraint if exists FK_ROLE_PREMISSIONS__REMISSION;
alter table if exists app_role_permission drop constraint if exists FK_ROLE_PREMISSIONS__ROLE;
alter table if exists app_user drop constraint if exists FK_USER__CONTACT;
alter table if exists app_user drop constraint if exists FK_USER__CREATED_BY;
alter table if exists app_user drop constraint if exists FK_USER__MODIFIED_BY;
alter table if exists app_user_role drop constraint if exists FK_USER_ROLES__ROLE;
alter table if exists app_user_role drop constraint if exists FK_USER_ROLES__USER;
alter table if exists audit_log drop constraint if exists FK_AUDIT_LOG__CREATED_BY;
alter table if exists audit_log drop constraint if exists FK_AUDIT_LOG__MODIFIED_BY;
alter table if exists contact drop constraint if exists FK_CONTACT__CREATED_BY;
alter table if exists contact drop constraint if exists FK_CONTACT__MODIFIED_BY;
alter table if exists customer_profile drop constraint if exists FK_CUSTOMER_PROFILE__CREATED_BY;
alter table if exists customer_profile drop constraint if exists FK_CUSTOMER_PROFILE__MODIFIED_BY;
alter table if exists holiday_booking drop constraint if exists FK_HOLIDAY_BOOKING__CREATED_BY;
alter table if exists holiday_booking drop constraint if exists FK_HOLIDAY_BOOKING__MODIFIED_BY;
alter table if exists holiday_booking_addon drop constraint if exists FK_HOLIDAY_BOOKING__ADDON;
drop table if exists app_permission cascade;
drop table if exists app_role cascade;
drop table if exists app_role_permission cascade;
drop table if exists app_user cascade;
drop table if exists app_user_role cascade;
drop table if exists audit_log cascade;
drop table if exists contact cascade;
drop table if exists customer_profile cascade;
drop table if exists holiday_booking cascade;
drop table if exists holiday_booking_addon cascade;
drop sequence if exists app_permission_seq;
drop sequence if exists app_role_seq;
drop sequence if exists app_user_seq;
drop sequence if exists audit_log_seq;
drop sequence if exists contact_seq;
drop sequence if exists customer_profile_seq;
drop sequence if exists holiday_booking_seq;
